[package]
name = "decv-audio"
version.workspace = true
edition.workspace = true
publish.workspace = true
authors.workspace = true

[dependencies]
decv-core = { path = "../decv-core" }
symphonia = { version = "0.6.0", default-features = false, features = ["all-codecs"] }

[dev-dependencies]
decv-mp4 = { path = "../decv-mp4" }
