[workspace]
resolver = "2"
members = [
  "crates/bit-readers",
  "crates/decv",
  "crates/decv-audio",
  "crates/decv-cli",
  "crates/decv-core",
  "crates/decv-h264",
  "crates/decv-mp4",
  "crates/decv-network",
]
[workspace.package]
publish = false
edition = "2024"
version = "0.1.0"
authors = ["cradiy.rs@gmail.com"]

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
