[package]
name = "decv-h264"
version.workspace = true
edition.workspace = true

[features]
internal-profiling = []

[dependencies]
bit-readers = { path = "../bit-readers" }
decv-core = { path = "../decv-core" }
memchr = "2.8.0"
rayon = "1.12.0"
smallvec = "1.15.1"

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "cavlc"
harness = false

[[bench]]
name = "inter_prediction"
harness = false
